import { mutation } from "./_generated/server";
import { nowIso, requireAdmin } from "./lib";

const sampleProducts = [
  {
    name: "Fortress of the Muslim",
    slug: "fortress-of-the-muslim",
    short_description: "A compact collection of daily supplications from the Qur'an and Sunnah.",
    description: "Pocket-friendly duas for morning, evening, travel, illness and everyday moments.",
    author: "Sa'id bin Ali bin Wahf Al-Qahtani",
    publisher: "Darussalam",
    language: "English",
    pages: 192,
    binding: "Paperback",
    price: 180,
    price_inr: 180,
    stock_quantity: 80,
    category: "books",
    tags: ["Hadith", "Tazkiyah"],
    cover_image_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    images: [],
    badge: "Bestseller",
    rating: 4.9,
    reviews_count: 128,
    is_active: true,
    is_featured: true,
    is_new_arrival: false,
    is_bestseller: true,
    is_on_sale: false,
    in_stock: true,
  },
  {
    name: "The Sealed Nectar",
    slug: "the-sealed-nectar",
    short_description: "Award-winning biography of Prophet Muhammad ﷺ.",
    description: "A detailed, accessible seerah volume for students and families.",
    author: "Safiur Rahman Mubarakpuri",
    publisher: "Darussalam",
    language: "English",
    pages: 588,
    binding: "Hardcover",
    price: 650,
    price_inr: 650,
    stock_quantity: 42,
    category: "books",
    tags: ["Seerah"],
    cover_image_url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80",
    images: [],
    badge: "Classic",
    rating: 4.8,
    reviews_count: 93,
    is_active: true,
    is_featured: true,
    is_new_arrival: false,
    is_bestseller: true,
    is_on_sale: false,
    in_stock: true,
  },
  {
    name: "Arabic Alphabet Flashcards",
    slug: "arabic-alphabet-flashcards",
    short_description: "Durable cards for young learners beginning Arabic letters.",
    description: "Large, clear letterforms with transliteration and playful practice prompts.",
    author: null,
    publisher: "Hurayrah Essentials",
    language: "Arabic / English",
    pages: 56,
    binding: "Card set",
    price: 299,
    price_inr: 299,
    stock_quantity: 70,
    category: "children",
    tags: ["Arabic", "Children"],
    cover_image_url: "https://images.unsplash.com/photo-1600189261867-30e5ffe7b8da?auto=format&fit=crop&w=800&q=80",
    images: [],
    badge: "New",
    rating: 4.7,
    reviews_count: 31,
    is_active: true,
    is_featured: false,
    is_new_arrival: true,
    is_bestseller: false,
    is_on_sale: false,
    in_stock: true,
  },
  {
    name: "Everyday Modest Thobe",
    slug: "everyday-modest-thobe",
    short_description: "A breathable everyday thobe with a clean, relaxed fit.",
    description: "Soft-touch fabric, easy movement and subtle detailing for daily wear.",
    author: null,
    publisher: "Hurayrah Essentials",
    language: null,
    pages: null,
    binding: null,
    price: 1299,
    price_inr: 1299,
    sale_price: 1099,
    sale_price_inr: 1099,
    stock_quantity: 24,
    category: "clothing",
    tags: ["Clothing"],
    cover_image_url: "https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=800&q=80",
    images: [],
    badge: "Sale",
    rating: 4.6,
    reviews_count: 18,
    is_active: true,
    is_featured: true,
    is_new_arrival: true,
    is_bestseller: false,
    is_on_sale: true,
    in_stock: true,
  },
];

export const seedSampleProducts = mutation({
  args: {},
  handler: async (ctx) => {
    await requireAdmin(ctx);
    const existing = await ctx.db.query("products").take(1);
    if (existing.length > 0) return { inserted: 0 };
    const timestamp = nowIso();
    for (const product of sampleProducts) {
      await ctx.db.insert("products", { ...product, created_at: timestamp, updated_at: timestamp });
    }
    return { inserted: sampleProducts.length };
  },
});
